= Notes

== Goals

* The main goal is to make a more "Gradley" Gradle plugin, especially:
  ** better leverage Gradle's up-to-date handling
  ** better leverage Gradle's task dependency capability
  ** more user-friendly DSL
* Prefer build-script handling of deployment-only settings (`quarkus.datasource.db-kind` e.g.)
* Seamless support for both Groovy and Kotlin based build scripts, especially IDE support for Kotlin scripts
* Be fast :)


== Design decisions

* Extensions modeled as `PolymorphicNamedDomainObjectContainer`:
 ** allows special DSL handling for individual extensions
 ** allows inclusion of arbitrary extensions


== Current limitations

* There is a large list of limitations based on the fact that Quarkus really has no support for any tooling providing any of the pieces of the build.  For example,
  even though the plugin has significantly better handling of Jandex indexes, there is no way to provide that Jandex index to Quarkus

== Tasks

* Clean up usages of Gradle's `Logger#lifecycle` method
* Review use of exception types
