= Notes

== Design decisions

* Extensions as `NamedDomainObjectContainer`.  Other option is to define specific config blocks for each extension which would require a-priori
knowledge of all available extensions
* At the moment, the extension blocks in the DSL are named based on their artifact name minus the `quarkus-` part.  E.g. `quarkus-hibernate-orm` ->
`hibernate-orm`.  That makes for a somewhat awkward handling in the DSL because the names have to be quoted due to the dash (subtraction):
```
modules {
    'hibernate-orm' {
        databaseFamily 'derby'
    }
}
```
* Extensions container named "modules".  Gradle augments the class to implement `ExtensionContainer` which defines a method `#getExtensions` which
precludes us being able to use that name.
* 2 separate tasks - `GenerateJarTask` and `GenerateFatJarTask`.  Might be better to have a config option and just adjust the standard `jar` as needed
based on that config value.
* Modeled both Jandex-indexing and augmentation as separate tasks.  I made this choice for a number of reasons:
 ** Better leverage Gradle's up-to-date checking - faster.
 ** Possibly useful during development to verify output.
 ** Better model step dependencies as Task dependencies
* At the moment I completely guessed regarding how we want to segment dependencies (per extension).  This will likely change
as the functionality (tasks) are implemented and requirements become more clear.


== Clean-up

* We need to go back and clean-up usages of Gradle's `Logger#lifecycle` method